services:
  - type: web
    name: remote-desktop-landing-page
    env: static
    buildCommand: "npm run build"
    staticPublishPath: "./dist"
    routes:
      - type: rewrite
        source: "/admin"
        destination: "/index.html"
      - type: rewrite
        source: "/**"
        destination: "/index.html"
